#!/usr/bin/python3
#coding=utf-8
################################# Credits ##########################################################
# Le credit pour ce code va a Mr Faxel
# Si vous voulez prendre Le credit pour ce code Voyez Faster Axel.
####################################################################################################
#\033[1;97m═╬══\033[1;91m►
####################################################################################################
# -Effacer le systeme en question-#
import os
def cls():
    os.system('clear')
####################################################################################################
raw_input = input
logo_faxel =("""\033[38;5;247m╭━╮╭━╮╱╱\033[38;5;214m╭━━━╮╱╱╱╱╱╱╱╱╭╮\n\033[38;5;247m┃┃╰╯┃┃╱╱\033[38;5;214m┃╭━━╯╱╱╱╱╱╱╱╱┃┃\n\033[38;5;247m┃╭╮╭╮┣━╮\033[38;5;214m┃╰━━┳━━┳╮╭┳━━┫┃\n\033[38;5;247m┃┃┃┃┃┃╭╯\033[38;5;214m┃╭━━┫╭╮┣╋╋┫┃━┫┃\n\033[38;5;247m┃┃┃┃┃┃┃╱\033[38;5;214m┃┃╱╱┃╭╮┣╋╋┫┃━┫╰╮\n\033[38;5;247m╰╯╰╯╰┻╯╱\033[38;5;214m╰╯╱╱╰╯╰┻╯╰┻━━┻━╯""")
####################################################################################################
# -Importation des modules-#
try:
    import os, time, sys, fileinput, datetime, random, requests, mechanize,datetime,urllib2,urllib, urllib.request,webbrowser
    from six.moves import input
    from mechanize import Browser
    from requests import get, post 
    from time import sleep
    print("\n\033[1;92m Exigences des modules disponibles")
except :
    cls()
    print("\033[1;95m Configuration requise pour l'installation....\033[1;97m")
    os.system('pip3 install requests')
    os.system('pip3 install mechanize')
    cls()
####################################################################################################
if sys.version[0] in '2':
    cls()
    print(logo_faxel)
    exit("\n\t\033[1;91m[\033[1;93m*\033[1;91m]\033[1;97m Vous ne pouvez pas utiliser\033[1;95m python2\033[1;97m pour executer ce script\033[1;97m.\n\t\033[1;91m[\033[1;93m*\033[1;91m]\033[1;97m Veuillez l'executer en tapant \033[38;5;247mpython3\n")
####################################################################################################
# -Automatisation-#
def mael(f):
    for l in f + '\n':
        sys.stdout.write(l)
        sys.stdout.flush()
        time.sleep(0.009)
        #time.sleep(1e-43)
####################################################################################################        
# -Effacer le systeme en question-#
def cls():
    os.system('clear')
####################################################################################################        
# -La date du jours courant-#
def horaire():
    os.system('date | lolcat')
    #print("\t\033[38;5;214m \033[1;31m  [\033[1;37m++\033[1;31m]\033[042m \033[1;37m Codé par\033[1;31m : \033[38;5;245m Mr \033[38;5;247mFaxel\033[1;31m [\033[1;37m++\033[1;31m] \033[00m")		
####################################################################################################
# -Animation a ma troisieme methode-#
def periode():
   periodique = ['.','..','...','....','.....']
   for o in periodique:
     print("\r\033[1;91m[●] \033[1;92mChargement en cours\033[1;97m"+o),;sys.stdout.flush();time.sleep(1)		
####################################################################################################	
########## -Au revoir- ##########
def bye():
     sys.exit()     
####################################################################################################	
########## -Arret animer- ##########
def arret():
    mael("\033[1;97m╔══╗─────╔╗───────────────╔═╗")
    mael("\033[1;97m║╔╗╠╦╦╦╦═╣╚╗╔═╦═╦╗╔═╦═╦╦╦╦╣═╣")
    mael("\033[1;91m║╠╣║╔╣╔╣╩╣╔╣║╩╣║║║║═╣╬║║║╔╬═║")
    mael("\033[1;91m╚╝╚╩╝╚╝╚═╩═╝╚═╩╩═╝╚═╩═╩═╩╝╚═╝")
    mael('\033[1;97m▒▒▒▒▒▒▒▒▒▒')
    print("\033[1;32m0%")
    mael('\033[1;97m█▒▒▒▒▒▒▒▒▒')
    print("\033[1;32m10%")
    mael('\033[1;97m███▒▒▒▒▒▒▒')
    print("\033[1;32m30%")
    mael('\033[1;97m█████▒▒▒▒▒')
    print("\033[1;32m50%")
    mael('\033[1;97m███████▒▒▒')
    print("\033[1;32m80%")
    mael('\033[1;97m██████████')
    print("\033[1;32m100%")
    mael("\n\033[1;97mBye Mec, j\'espere que tu as adorée le script de\033[1;91m Mr \033[1;96mFaxel\033[1;97m.A bientot!!\n")
    bye()
####################################################################################################
# -Chargement a ma deuxieme methode-#
def load(mot):
    chaine = [
     '/', '-', '|']
    for i in range(5):
        for x in range(len(chaine)):
            sys.stdout.write(('\r{}{}').format(str(mot), chaine[x]))
            time.sleep(0.3)
            sys.stdout.flush()
####################################################################################################  
# -Chargement a ma premiere methode-#
def charge():
    compteur = ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100"]
    print
    for b in compteur:
    	sys.stdout.write("\r\033[1;91m[\033[1;93m*\033[1;91m] \033[38;5;245m@\033[38;5;221mFaxel\033[1;92m "+b+" \033[1;97m%")
    	sys.stdout.flush()
    	time.sleep(0.1)
    time.sleep(1.5)
####################################################################################################
logo =("""\033[38;5;214m●▬▬▬▬▬▬▬▬๑\033[1;97m●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬●●▬▬▬▬▬\033[1;32m▬▬▬▬๑۩۩๑▬▬▬▬▬▬●            \n\033[38;5;214m•_  _ ____ \033[1;97m _  _ ____ ____ _  _\033[1;32m ____ ____   _  _• \n\033[38;5;214m•|\/| |__/ \033[1;97m |__| |__| |    |_/ \033[1;32m |___ |__/   |_/ • \n\033[38;5;214m•|  | |  \ \033[1;97m |  | |  | |___ | \_\033[1;32m |___ |  \ __| \_•    \n\033[38;5;214m●▬▬▬▬▬▬▬▬๑\033[1;97m●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬●●▬▬▬▬▬\033[1;32m▬▬▬▬๑۩۩๑▬▬▬▬▬▬●\n\033[1;97m╔═════════════════════════════════════════════╗\n\033[1;97m║\033[1;91m[\033[1;93m**\033[1;91m]\033[38;5;95m      Developpeur \033[1;97m:\033[38;5;214m  Faxel           \033[1;91m[\033[1;93m**\033[1;91m]\033[1;97m║\n\033[1;97m╚═════════════════════════════════════════════╝""")
logo_ndao =("""\x1b[1;32m╔════╗─────\x1b[1;37m╔╗─╔╗─────╔╗\n\x1b[1;32m║╔╗╔╗║─────\x1b[1;37m║║─║║─────║║\n\x1b[1;32m╚╝║║╠╩═╦══╗\x1b[1;37m║╚═╝╠══╦══╣║╔╦╦═╗╔══╗\n\x1b[1;32m──║║║╔╗║╔╗║\x1b[1;37m║╔═╗║╔╗║╔═╣╚╝╬╣╔╗╣╔╗║\n\x1b[1;32m──║║║╚╝║╚╝║\x1b[1;37m║║─║║╔╗║╚═╣╔╗╣║║║║╚╝║\n\x1b[1;32m──╚╝╚══╣╔═╝\x1b[1;37m╚╝─╚╩╝╚╩══╩╝╚╩╩╝╚╩═╗║\n\x1b[1;32m───────║║──\x1b[1;37m─────────────────╔═╝║\n\x1b[1;32m───────╚╝──\x1b[1;37m─────────────────╚══╝ """)
logo_ach =("""\033[38;5;214m╭━━╮╱╱╱╱╱╱╱╱╱╱\033[38;5;136m╭╮╭╮╱╱╱╱╭╮\n\033[38;5;214m╰╮╭┻┳┳┳━━┳┳┳┳╮\033[38;5;136m┃╰╯┣━╮╭━┫┣╮\n\033[38;5;214m╱┃┃┻┫╭┫┃┃┃┃┣┃┫\033[38;5;136m┃╭╮┃╋╰┫━┫━┫\n\033[38;5;214m╱╰┻━┻╯╰┻┻┻━┻┻╯\033[38;5;136m╰╯╰┻━━┻━┻┻╯ """)
logo_youtube =("""\033[38;5;214m╔═══╗─────╔╗─\x1b[1;37m─────╔══\x1b[1;32m═╗─────╔╗\n\033[38;5;214m║╔══╝────╔╝╚╗\x1b[1;37m─────║╔═\x1b[1;32m╗║─────║║\n\033[38;5;214m║╚══╦══╦═╩╗╔╬\x1b[1;37m══╦═╗║║─\x1b[1;32m║╠╗╔╦══╣║\n\033[38;5;214m║╔══╣╔╗║══╣║║\x1b[1;37m║═╣╔╝║╚═\x1b[1;32m╝╠╬╬╣║═╣║\n\033[38;5;214m║║──║╔╗╠══║╚╣\x1b[1;37m║═╣║─║╔═\x1b[1;32m╗╠╬╬╣║═╣╚╗\n\033[38;5;214m╚╝──╚╝╚╩══╩═╩\x1b[1;37m══╩╝─╚╝─\x1b[1;32m╚╩╝╚╩══╩═╝""")
logo_sec =("""\x1b[1;32m╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╭╮╱╱╱╱╱\033[38;5;214m ╭━━━╮╱╱╱╱╱╱╱╱╭╮\n\x1b[1;32m┃╭━╮┃╱╱╱╱╱╱╱╱╱╱╭╯╰╮╱╱╱╱\033[38;5;214m ┃╭━━╯╱╱╱╱╱╱╱╱┃┃\n\x1b[1;32m┃╰━━┳━━┳━━┳╮╭┳━╋╮╭╋╮╱╭╮\033[38;5;214m ┃╰━━┳━━┳╮╭┳━━┫┃\n\x1b[1;32m╰━━╮┃┃━┫╭━┫┃┃┃╭╋┫┃┃┃╱┃┃\033[38;5;214m ┃╭━━┫╭╮┣╋╋┫┃━┫┃\n\x1b[1;32m┃╰━╯┃┃━┫╰━┫╰╯┃┃┃┃╰┫╰━╯┃\033[38;5;214m ┃┃╱╱┃╭╮┣╋╋┫┃━┫╰╮\n\x1b[1;32m╰━━━┻━━┻━━┻━━┻╯╰┻━┻━╮╭╯\033[38;5;214m ╰╯╱╱╰╯╰┻╯╰┻━━┻━╯\n\x1b[1;32m╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃\n\x1b[1;32m╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯\n\033[1;97m╔═════════════════════════════════════════════╗\n\033[1;97m║\033[1;91m[\033[1;93m**\033[1;91m]\033[38;5;95m      Developpeur \033[1;97m:\033[38;5;214m  Faxel           \033[1;91m[\033[1;93m**\033[1;91m]\033[1;97m║\n\033[1;97m╚═════════════════════════════════════════════╝""")
logo_faxel =("""\033[38;5;214m──\033[38;5;125m▄\033[38;5;214m────\033[38;5;125m▄▄▄▄▄▄▄\033[38;5;214m────\033[38;5;125m▄\033[38;5;214m───\n\033[38;5;214m─\033[38;5;125m▀▀▄\033[38;5;214m─\033[38;5;125m▄█████████▄\033[38;5;214m─\033[38;5;125m▄▀▀\033[38;5;214m──\n\033[38;5;214m─────\033[38;5;125m██\033[38;5;214m─\033[38;5;125m▀███▀\033[38;5;214m─\033[38;5;214m██\033[38;5;214m──────\n\033[38;5;214m───\033[38;5;125m▄\033[38;5;214m─\033[38;5;125m▀████▀████▀\033[38;5;214m─\033[38;5;125m▄\033[38;5;214m────\n\033[38;5;214m─\033[38;5;125m▀█\033[38;5;214m────\033[38;5;125m██▀█▀██\033[38;5;214m────\033[38;5;125m█▀\033[38;5;214m──\n\033[38;5;214m█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█\n\033[38;5;214m█░░\033[38;5;245m╦─╦╔╗╦─╔╗╔╗╔╦╗╔╗\033[38;5;214m░░█\n\033[38;5;214m█░░\033[38;5;245m║║║╠─║─║─║║║║║╠─\033[38;5;214m░░█\n\033[38;5;214m█░░\033[38;5;245m╚╩╝╚╝╚╝╚╝╚╝╩─╩╚╝\033[38;5;214m░░█\n\033[38;5;214m█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n\033[1;37mLa gestion dépend du logiciel VPN. Veuillez l'utiliser avant d'exécuter l'outil""")
####################################################################################################
####################################################################################################
####################################################################################################
def securite():
    cls()
    horaire()
    print(logo_sec)
    nom_u = 'Faxel'
    mdp = '08127934'
    print("\033[1;97m║")
    user = raw_input("\033[1;97m╬═\033[1;31m▶\033[38;5;245m NOM D'UTILISATEUR \033[1;97m═╬══\033[1;91m► \033[1;92m")
    if user == nom_u:
        pass
    elif not user == nom_u:
        print ("\n\033[1;91m[\033[1;93m*\033[1;91m]\033[1;95m Nom d'utilisateur incorrect!")
        os.system('xdg-open https://wa.me/22555709610')
        securite()
    print("\033[1;97m║")
    mot_passant = raw_input("\033[1;97m╬═\033[1;31m▶\033[38;5;245m MOT DE PASSE      \033[1;97m═╬══\033[1;91m► \033[1;93m")
    print("\033[1;97m╚═════════════════════════════════════════════╝")
    if mot_passant == mdp:
        load("\033[1;97m Chargement en cours\033[1;92m...")
        print("\n\033[1;91m[\033[1;93m!\033[1;91m]\033[1;92m Connexion réussie ")
        Menu()
    elif not mot_passant == mdp:
        print ("\n\033[1;91m[\033[1;93m*\033[1;91m]\033[1;95m Mot de passe incorrect!")
        os.system('xdg-open https://t.me/Faxelh')
        securite()
####################################################################################################     
def Menu():
    cls()
    horaire()
    print(logo)
    print("\033[1;97m╔"+37*"═"+1*"═╗")
    print("\033[1;97m║ \033[1;91m[\033[1;96m1.\033[1;91m]\033[38;5;214m Phase a la recherche User       \033[1;97m║")
    print("\033[1;97m║ \033[1;91m[\033[1;96m2.\033[1;91m]\033[38;5;121m Abonnez-vous à ma chaîne youtube\033[1;97m║") 
    print("\033[1;97m║ \033[1;91m[\033[1;96m3.\033[1;91m]\033[38;5;136m Groupe Telegram N°1             \033[1;97m║") 
    print("\033[1;97m║ \033[1;91m[\033[1;96m4.\033[1;91m]\033[38;5;125m Groupe Telegram N°2             \033[1;97m║") 
    print("\033[1;97m╚"+37*"═"+1*"═╝") 
    print("\033[1;97m║")
    choix_menu()
def choix_menu():
    dmd = raw_input("\033[1;97m╚═\033[1;31m▶\033[38;5;245m Mr \033[38;5;221mFaxel \033[1;97m═╬══\033[1;91m► \033[1;96m" )
    if dmd =="":
        print("\n\t\033[1;91m[\033[1;93m!\033[1;91m]\033[1;95m Remplissez correctement ")
        Menu()
    elif dmd =="1":
        user_found()
    elif dmd =="2":
        cls()
        print(logo_youtube)
        mael("\033[1;91m[\033[1;93m!\033[1;91m]\033[1;96m Chaîne YouTube FASTER AXEL " )
        os.system('xdg-open https://www.youtube.com/c/FASTERAXEL?sub_confirmation=1')
        raw_input('\n\033[1;91m [\033[1;93m!\033[1;91m]\033[1;97m Appuyer entrer pour retourner au menu\033[1;93m...')
        Menu()
    elif dmd =="3":
        cls()
        print(logo_ach)
        mael("\033[1;91m[\033[1;93m!\033[1;91m]\033[1;96m Groupe Telegram A-C H ==TERMUX " )
        os.system('xdg-open https://t.me/Hacker_Termux1')
        raw_input('\n\033[1;91m [\033[1;93m!\033[1;91m]\033[1;97m Appuyer entrer pour retourner au menu...')
        Menu()
    elif dmd =="4":
        cls()
        print(logo_ndao)
        mael("\033[1;91m[\033[1;93m!\033[1;91m]\033[1;96m Groupe Telegram Top Hacking" )
        os.system('xdg-open https://t.me/NDAOKING')
        raw_input('\n\033[1;91m [\033[1;93m!\033[1;91m]\033[1;97m Appuyer entrer pour retourner au menu...')
        Menu()
    else:
        print('\n\x1b[1;91m[\xe2\x9c\x96] \x1b[1;97m '+dmd+' \x1b[1;91mindisponible')
        raw_input('\n\033[1;91m [\033[1;93m!\033[1;91m]\033[1;97m Appuyer entrer pour retourner au menu...')
        Menu()    
####################################################################################################
def user_found():
    cls()
    print(logo_faxel)
    print("\033[1;97m║")
    _requete_en_cours = raw_input("\n\033[1;97m╚═\033[1;31m▶\033[38;5;245m Entrer un nom d'utilisateur \033[1;97m═╬══\033[1;91m► \033[1;96m")
    lien = {
        'https://www.facebook.com',
        'https://twitter.com',
        'https://www.instagram.com',
        'https://www.youtube.com/user',
        'https://www.producthunt.com/@',
        'https://www.pinterest.com',
        'https://www.flickr.com/people',
        'https://vimeo.com',
        'https://soundcloud.com',
        'https://disqus.com',
        'https://medium.com/@',
        'https://about.me',
        'https://flipboard.com',
        'https://slideshare.net',
        'https://open.spotify.com/user',
        'https://www.scribd.com',
        'https://www.patreon.com',
        'https://bitbucket.org',
        'https://gitlab.com',
        'https://www.github.com',
        'https://www.goodreads.com',
        'https://www.instructables.com/member',
        'https://www.codecademy.com',
        'https://en.gravatar.com',
        'https://pastebin.com/u',
        'https://foursquare.com',
        'https://tripadvisor.com/members',
        'https://www.wikipedia.org/wiki/User:',
        'https://news.ycombinator.com/user?id=',
        'https://www.codementor.io',
        'https://www.trip.skyscanner.com/user',
        'https://blogspot.com',
        'https://wordpress.com',
        'https://tumblr.com',
        'https://livejournal.com',
        'https://slack.com',
        'https://ask.fm',
        'https://www.snapchat.com/add',
        'https://www.tiktok.com/@',
        'https://haraj.com.sa/users',
        'https://t.me/',
   }
    for lien_2 in lien :
        lien_3 = lien_2 +"/"+_requete_en_cours    
        try :  
            _ouverture_url = urllib.request._ouverture_url(lien_3)    
            print( lien_3 + " ==> \n\033[1;92m Bon ")  
        except urllib.error.URLError as msg :       
                    print( lien_3 + " ==> \n\033[1;91m Desolé ")   
    load("\033[1;91m[\033[1;93m!\033[1;91m]\033[1;95mLa recherche de tweets d'utilisateurs est en cours")
    print("\n")
    recherche = webbrowser.open_new("https://mobile.twitter.com/search?q="+_requete_en_cours+"")        
    load("\033[1;91m[\033[1;93m+\033[1;91m]\033[1;97m Recherche de l'utilisateur dans Google\033[1;92m...")
    print("\n")
    reche = webbrowser.open_new('http://www.google.com/search?q='+_requete_en_cours+'&pov=107128685182183119625&usg=__uAMtO0js_mAj03ni57W7YeWKuB8=&hl=ar')
    raw_input('\n\033[1;91m[\033[1;93m+\033[1;91m]\033[1;97m Appuyer entrer pour retourner au menu\033[1;92m...')
    Menu()     
####################################################################################################
####################################################################################################            
if __name__ == '__main__':
      security()
###################################################################################################
